### ISSUE TITLE
"No devices are booted" when launching SpringBoard

### ISSUE THREAD

**Issue by BasThomas** [DeskConnect/SBShortcutMenuSimulator#2]
```
Bas-iMac:SBShortcutMenuSimulator bas$ xcrun simctl spawn booted launchctl debug system/com.apple.SpringBoard --environment DYLD_INSERT_LIBRARIES=$PWD/SBShortcutMenuSimulator.dylib
No devices are booted.
Bas-iMac:SBShortcutMenuSimulator bas$ xcrun simctl spawn booted launchctl stop com.apple.SpringBoard
No devices are booted.
Bas-iMac:SBShortcutMenuSimulator bas$
```

**Comment by TinyGiantDigital** [comment]
I had this issue, just run the 2 commands whilst the simulator is running works fine

**Comment by BasThomas** [comment]
Calling `echo 'com.apple.mobilecal' | nc 127.0.0.1 8000` afterwards doesn't do anything for me, though.

**Comment by AriX** [comment]
Was the iPhone simulator running while you ran the xcrun simctl commands? It needs to be, otherwise it won't work.

**Comment by BasThomas** [comment]
Yes, it was.

**Comment by AriX** [comment]
Try rebooting your machine and doing it again, and/or quit Xcode and use Activity Monitor to force quit all instances of the Core Simulator service and try it again.

**Comment by BasThomas** [comment]
That didn't do the trick, unfortunately. Running 10.11, build number 15A279b. Might that have something to do with it?

**Comment by BasThomas** [comment]
Ah, confirmed working in Xcode 7.0.1, not working in Xcode 7.1 beta 3 (7B75).

**Comment by BasThomas** [comment]
... getting the same error again, even on 7.0.1.

**Comment by ghost** [comment]
I am using Xcode 7.0 and facing same issue... "No devices are booted." message comes when  execute command:

xcrun simctl spawn booted launchctl debug system/com.apple.SpringBoard --environment DYLD_INSERT_LIBRARIES=$PWD/SBShortcutMenuSimulator.dylib

My simulator is on. I even restarted it, but didn't succeed. I hope so this command doesn't require any more special steps... Any idea @AriX ?

Thanks.

**Comment by ghost** [comment]
It worked now. Sorry I misinterpreted info. Whoever come across this thread, please make sure:

1) You have set Xcode 7 as default xcode app. Do it by command:
sudo xcode-select -switch "/Applications/Xcode.app"

2) Then from the "SBShortcutMenuSimulator" directory, run those two commands.

3) After simulator is restarted, run command as told in doc:
echo 'your.app.bundle.id' | nc 127.0.0.1 8000

**Comment by SaketGupte** [comment]
@Anum-Amin thanks. Was facing a similar issue. Your solution solved the problem. However running echo 'com.apple.mobilecal' | nc 127.0.0.1 8000 doesn't do anything. Does anybody have a solution for that?

**Comment by ghost** [comment]
@SaketGupte Make sure simulator is running and you are on home screen. The app whose name you pass in the mentioned command must support Application shortcut menu else nothing will happen. I don't think that `com.apple.mobilecal` supports Shortcut Menu.
