### ISSUE TITLE
Failed to run the given command

### ISSUE THREAD

**Issue by MittaKarthik** [DeskConnect/SBShortcutMenuSimulator#4]
I am using xcode 7.0.1 (latest version) Find the output after running the given command 

Invalid environment variable specifier: Data/Personal
Usage: launchctl debug <service-target> [--program <program-path>] [--start-suspended] [--guard-malloc] [--malloc-stack-logging] [--malloc-nano-allocator] [--debug-libraries] [--NSZombie] [--32] [--stdin [path]] [--stdout [path]] [--stderr [path]] [--environment VARIABLE0=value0 VARIABLE1=value1 ...] -- [argv0 argv1 ...]
        --program
                Use a different binary for the service's executable.
        --start-suspended
                Start the process suspended.
        --guard-malloc
                Enable libgmalloc(3) for the service.
        --malloc-stack-logging
                Enable malloc(3) stack logging.
        --malloc-nano-allocator
                Enables the malloc(3) nano allocator.
        --debug-libraries
                Sets DYLD_IMAGE_SUFFIX to "_debug".
        --NSZombie
                Enables NSZombie
        --32    Runs the service in 32-bit mode (only available on 64-bit
                platforms).
        --stdin
                When an argument is given, the file at that path is used as the
                service's stdin. With no argument, the current terminal is used
                as the service's stdin.
        --stdout
                When an argument is given, the file at that path is used as the
                service's stdout. With no argument, the current terminal is
                used as the service's stdout.
        --stderr
                When an argument is given, the file at that path is used as the
                service's stderr. With no argument, the current terminal is
                used as the service's stderr.
        --environment
                Set environment variables on the service.

**Comment by conradev** [comment]
Try this instead:

```
xcrun simctl spawn booted launchctl debug system/com.apple.SpringBoard --environment DYLD_INSERT_LIBRARIES="${PWD}/SBShortcutMenuSimulator.dylib"
```

**Comment by MittaKarthik** [comment]
Wah..!! It's working. Thank you.
