### ISSUE TITLE
Why does iPhone 6 PLUS simulator supports 3D touch?

### ISSUE THREAD

**Issue by tounaobun** [DeskConnect/SBShortcutMenuSimulator#5]
Why does iPhone 6 PLUS simulator supports 3D touch?https://raw.githubusercontent.com/DeskConnect/SBShortcutMenuSimulator/screenshot/Shortcuts.png

**Comment by AriX** [comment]
Not sure - likely Apple didn't take the time to check in SpringBoard what model of device you're running it on. But this is not an issue with this project :)
