### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by andres-cianio** [DeskConnect/SBShortcutMenuSimulator#6]
Hi there,

This is a great idea, thanks for sharing it!! Unfortunately, it doesn't seem to be working for me...
I'm using `Xcode Version 7.0.1 (7A1001)` with `Simulator Version 9.0 (SimulatorApp-620 CoreSimulator-179)`.

I've cloned the repo, built it with `make` and then run the `debug` command with both Xcode and the Simulator open. Result was: `Service configured for next launch.`

Then I tried sending the signal with my own bundle ID, but also with the Calendar one shown in the example, and never got any output on the Terminal, nor anything that happened in the simulator.

Is it possible I'm missing some step, previous configuration, dependency? Any further info that may be of service?

Thanks in advance!

**Comment by andres-cianio** [comment]
Never mind! [This issue](https://github.com/DeskConnect/SBShortcutMenuSimulator/issues/2) had the solution.

**Comment by venn0126** [comment]
how to solute???
Thans in advance
