### ISSUE TITLE
ForceTouchCapability return value

### ISSUE THREAD

**Issue by loregr** [DeskConnect/SBShortcutMenuSimulator#8]
if I call [[self.window.rootViewController traitCollection] forceTouchCapability] in AppDelegate, it returns UIForceTouchCapabilityUnavailable on iPhone 6s simulator. Someone with a real device, can tell me if it's normal and on a real iPhone 6s it returns UIForceTouchCapabilityAvailable instead?

Thanks

**Comment by hansemannn** [comment]
It's normal, since the simulator does not support it. You can use the API with this hack, but it does not set system properties.

**Comment by loregr** [comment]
cool...thanks @hansemannn
