### ISSUE TITLE
how to uninstall it?

### ISSUE THREAD

**Issue by LJson** [DeskConnect/SBShortcutMenuSimulator#9]
it not work on my Xcode 7,so please tell me how to uninstall it.now,the iphonesimulator's SpringBoard is just a black view.

**Comment by LJson** [comment]
after installed it ,the iphonesimulator which version less than iPhone6s, SpringBoard is just a black view.but i need to use the iPhone 6 iphonesimulator,please tell me how to uninstall it.thanks a lot.

**Comment by simme** [comment]
Looking at the `Makefile` it seems like `make clean` from the repo directory should do the trick.

**Comment by conradev** [comment]
Either `make clean` or simply deleting the downloaded folder should do the trick!
